# See: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: storybook-page
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: git config user.email "bot@smuj.dev"
    - run: git config user.name "Smuj Bot"
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run deploy-storybook
      env:
        PUBLIC_URL: "/react-canvas-resize/"
